package org.batch.exceptionhandling.trycatchfinally.interview;

public class TryWithMultipleCatchWithExceptionClass {


    public static void main(String[] args) {
    /*    try{
            System.out.println("line-1");
            System.out.println("line-2");
            System.out.println("line-3");
            int a = 10/0;                   //java.lang.ArithmeticException: / by zero
            System.out.println("line-4");
            System.out.println("line-5");
        }catch (Exception e ){  //java: exception java.lang.ArithmeticException has already been caught
            System.out.println("Catch block  ArithmeticException" );
        }catch (ArithmeticException e ){
            System.out.println("Catch block  ArithmeticException" );
        }
*/

        System.out.println("code completed gracefully");
    }
}
